const skillsData: string[] = [
  "HTML/CSS/JavaScript",
  "SASS/SCCS",
  "React.js",
  "Redux (Toolkit, Saga)",
  "TypeScript",
  "React Native",
  "Next.js",
  "Storybook",
  "Tailwind CSS",
  "Bootstrap 5.0",
  "Docker",
  "MySQL/PostgresSQL",
  "MongoDB",
  "Sequelize ORM",
  "Node.js",
  "Nest.js",
  "Git",
  "REST",
  "i18next",
  "C/C++",
  "Python",
];

export default skillsData;
